version: "3.9"
services:
  mysql:
    image: mysql:8.4
    container_name: payments-mysql
    environment:
      MYSQL_DATABASE: payment_db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
      TZ: UTC
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
